# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeliveryTas1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2
import PublicTas1_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DeliveryTas1.proto',
  package='DeliveryTas1',
  serialized_pb='\n\x12\x44\x65liveryTas1.proto\x12\x0c\x44\x65liveryTas1\x1a\x0c\x63ommon.proto\x1a\x10PublicTas1.proto\"}\n\rDeliveryAudit\x12\x1c\n\x06Header\x18\x01 \x01(\x0b\x32\x0c.MessageHead\x12\x0f\n\x07RetCode\x18\x02 \x01(\x05\x12\x12\n\nDeliveryID\x18\x03 \x02(\x03\x12\x11\n\tAuditName\x18\x04 \x02(\t\x12\x16\n\x0e\x44\x65liveryStatus\x18\x05 \x02(\x05\"~\n\x10\x44\x65liveryAuditRsp\x12\x1c\n\x06Header\x18\x01 \x01(\x0b\x32\x0c.MessageHead\x12\x0f\n\x07RetCode\x18\x02 \x01(\x05\x12\x0f\n\x07RetDesc\x18\x03 \x01(\t\x12\x12\n\nDeliveryID\x18\x04 \x02(\x03\x12\x16\n\x0e\x44\x65liveryStatus\x18\x05 \x02(\x05')




_DELIVERYAUDIT = _descriptor.Descriptor(
  name='DeliveryAudit',
  full_name='DeliveryTas1.DeliveryAudit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Header', full_name='DeliveryTas1.DeliveryAudit.Header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RetCode', full_name='DeliveryTas1.DeliveryAudit.RetCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeliveryID', full_name='DeliveryTas1.DeliveryAudit.DeliveryID', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AuditName', full_name='DeliveryTas1.DeliveryAudit.AuditName', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeliveryStatus', full_name='DeliveryTas1.DeliveryAudit.DeliveryStatus', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=193,
)


_DELIVERYAUDITRSP = _descriptor.Descriptor(
  name='DeliveryAuditRsp',
  full_name='DeliveryTas1.DeliveryAuditRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Header', full_name='DeliveryTas1.DeliveryAuditRsp.Header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RetCode', full_name='DeliveryTas1.DeliveryAuditRsp.RetCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RetDesc', full_name='DeliveryTas1.DeliveryAuditRsp.RetDesc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeliveryID', full_name='DeliveryTas1.DeliveryAuditRsp.DeliveryID', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeliveryStatus', full_name='DeliveryTas1.DeliveryAuditRsp.DeliveryStatus', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=195,
  serialized_end=321,
)

_DELIVERYAUDIT.fields_by_name['Header'].message_type = common_pb2._MESSAGEHEAD
_DELIVERYAUDITRSP.fields_by_name['Header'].message_type = common_pb2._MESSAGEHEAD
DESCRIPTOR.message_types_by_name['DeliveryAudit'] = _DELIVERYAUDIT
DESCRIPTOR.message_types_by_name['DeliveryAuditRsp'] = _DELIVERYAUDITRSP

class DeliveryAudit(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELIVERYAUDIT

  # @@protoc_insertion_point(class_scope:DeliveryTas1.DeliveryAudit)

class DeliveryAuditRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELIVERYAUDITRSP

  # @@protoc_insertion_point(class_scope:DeliveryTas1.DeliveryAuditRsp)


# @@protoc_insertion_point(module_scope)
