# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExterReportTas1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import common_pb2
import PublicTas1_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExterReportTas1.proto',
  package='ExterReportTas1',
  serialized_pb='\n\x15\x45xterReportTas1.proto\x12\x0f\x45xterReportTas1\x1a\x0c\x63ommon.proto\x1a\x10PublicTas1.proto\"3\n\x13UniteExterReportReq\x12\x1c\n\x06Header\x18\x01 \x01(\x0b\x32\x0c.MessageHead\"U\n\x13UniteExterReportRsp\x12\x1c\n\x06Header\x18\x01 \x01(\x0b\x32\x0c.MessageHead\x12\x0f\n\x07RetCode\x18\x02 \x01(\x05\x12\x0f\n\x07RetDesc\x18\x03 \x01(\t')




_UNITEEXTERREPORTREQ = _descriptor.Descriptor(
  name='UniteExterReportReq',
  full_name='ExterReportTas1.UniteExterReportReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Header', full_name='ExterReportTas1.UniteExterReportReq.Header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=74,
  serialized_end=125,
)


_UNITEEXTERREPORTRSP = _descriptor.Descriptor(
  name='UniteExterReportRsp',
  full_name='ExterReportTas1.UniteExterReportRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Header', full_name='ExterReportTas1.UniteExterReportRsp.Header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RetCode', full_name='ExterReportTas1.UniteExterReportRsp.RetCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RetDesc', full_name='ExterReportTas1.UniteExterReportRsp.RetDesc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=127,
  serialized_end=212,
)

_UNITEEXTERREPORTREQ.fields_by_name['Header'].message_type = common_pb2._MESSAGEHEAD
_UNITEEXTERREPORTRSP.fields_by_name['Header'].message_type = common_pb2._MESSAGEHEAD
DESCRIPTOR.message_types_by_name['UniteExterReportReq'] = _UNITEEXTERREPORTREQ
DESCRIPTOR.message_types_by_name['UniteExterReportRsp'] = _UNITEEXTERREPORTRSP

class UniteExterReportReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNITEEXTERREPORTREQ

  # @@protoc_insertion_point(class_scope:ExterReportTas1.UniteExterReportReq)

class UniteExterReportRsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNITEEXTERREPORTRSP

  # @@protoc_insertion_point(class_scope:ExterReportTas1.UniteExterReportRsp)


# @@protoc_insertion_point(module_scope)
