# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  serialized_pb='\n\x0c\x63ommon.proto\"j\n\x0bMessageHead\x12\x0f\n\x07\x46unCode\x18\x01 \x01(\r\x12\x11\n\tRequestID\x18\x02 \x01(\r\x12\x11\n\tAccountId\x18\x03 \x01(\r\x12\x10\n\x08\x41\x63\x63\x65ssId\x18\x04 \x01(\r\x12\x12\n\nClientTime\x18\x05 \x01(\x03\"\x8e\x01\n\x10QueryReqPageInfo\x12\x12\n\nPageNumber\x18\x01 \x01(\x05\x12\x15\n\rRecordPerPage\x18\x02 \x01(\x05\x12\x11\n\tQueryMark\x18\x03 \x01(\x05\x12\x11\n\tSortField\x18\x04 \x01(\t\x12\x11\n\tSortOrder\x18\x05 \x01(\x05\x12\x16\n\x0eNeedTotalCount\x18\x06 \x01(\x05\"\x9f\x01\n\x10QueryRspPageInfo\x12\x12\n\nPageNumber\x18\x01 \x01(\x05\x12\x15\n\rRecordPerPage\x18\x02 \x01(\x05\x12\x11\n\tQueryMark\x18\x03 \x01(\x05\x12\x11\n\tSortField\x18\x04 \x01(\t\x12\x11\n\tSortOrder\x18\x05 \x01(\x05\x12\x13\n\x0bRecordCount\x18\x06 \x01(\x05\x12\x12\n\nTotalCount\x18\x07 \x01(\x05\"-\n\rCommonPackage\x12\x1c\n\x06Header\x18\x01 \x02(\x0b\x32\x0c.MessageHead')




_MESSAGEHEAD = _descriptor.Descriptor(
  name='MessageHead',
  full_name='MessageHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FunCode', full_name='MessageHead.FunCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RequestID', full_name='MessageHead.RequestID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='MessageHead.AccountId', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AccessId', full_name='MessageHead.AccessId', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ClientTime', full_name='MessageHead.ClientTime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=122,
)


_QUERYREQPAGEINFO = _descriptor.Descriptor(
  name='QueryReqPageInfo',
  full_name='QueryReqPageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PageNumber', full_name='QueryReqPageInfo.PageNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RecordPerPage', full_name='QueryReqPageInfo.RecordPerPage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QueryMark', full_name='QueryReqPageInfo.QueryMark', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SortField', full_name='QueryReqPageInfo.SortField', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SortOrder', full_name='QueryReqPageInfo.SortOrder', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NeedTotalCount', full_name='QueryReqPageInfo.NeedTotalCount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=125,
  serialized_end=267,
)


_QUERYRSPPAGEINFO = _descriptor.Descriptor(
  name='QueryRspPageInfo',
  full_name='QueryRspPageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PageNumber', full_name='QueryRspPageInfo.PageNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RecordPerPage', full_name='QueryRspPageInfo.RecordPerPage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QueryMark', full_name='QueryRspPageInfo.QueryMark', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SortField', full_name='QueryRspPageInfo.SortField', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SortOrder', full_name='QueryRspPageInfo.SortOrder', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RecordCount', full_name='QueryRspPageInfo.RecordCount', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TotalCount', full_name='QueryRspPageInfo.TotalCount', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=270,
  serialized_end=429,
)


_COMMONPACKAGE = _descriptor.Descriptor(
  name='CommonPackage',
  full_name='CommonPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Header', full_name='CommonPackage.Header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=431,
  serialized_end=476,
)

_COMMONPACKAGE.fields_by_name['Header'].message_type = _MESSAGEHEAD
DESCRIPTOR.message_types_by_name['MessageHead'] = _MESSAGEHEAD
DESCRIPTOR.message_types_by_name['QueryReqPageInfo'] = _QUERYREQPAGEINFO
DESCRIPTOR.message_types_by_name['QueryRspPageInfo'] = _QUERYRSPPAGEINFO
DESCRIPTOR.message_types_by_name['CommonPackage'] = _COMMONPACKAGE

class MessageHead(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEHEAD

  # @@protoc_insertion_point(class_scope:MessageHead)

class QueryReqPageInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYREQPAGEINFO

  # @@protoc_insertion_point(class_scope:QueryReqPageInfo)

class QueryRspPageInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYRSPPAGEINFO

  # @@protoc_insertion_point(class_scope:QueryRspPageInfo)

class CommonPackage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMONPACKAGE

  # @@protoc_insertion_point(class_scope:CommonPackage)


# @@protoc_insertion_point(module_scope)
